version: '3'
services:
  base-project:
    build:
      context: ../
      dockerfile: Dockerfile.prd
    image: base-project:lastest
    container_name: base-project
    restart: unless-stopped
#    env_file: ../.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=dev
    ports:
      - '3030:3030'
    volumes:
      - '.:/usr/src/app'
    command: yarn start
