version: '3'
services:
  base-project:
    build:
      context: ../
      dockerfile: scripts/Dockerfile.prd
    restart: always
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - DB_NAME=prod_sohoa
      - DB_CONNECTION_URI=mongodb://127.0.0.1:27017/sohoa #cáu hình cho ami
      - ELASTIC_SEARCH=http://127.0.0.1:9200 #cáu hình cho ami
      - ELASTIC_INDEX=data
    #    ports:
    #      - '13030:3030'
    #    volumes:
    #
    command: /APP
